### ISSUE TITLE
Config endpoint locks up with wallet: True when Faucet is unresponsive

### ISSUE THREAD

**Issue by fijter** [iotaledger/industry-marketplace#44]
When I call the `/config` endpoint it hangs and eventually times out in my client because it can't reach the faucet at this moment. Ideally it should never hang on this, can this be non-blocking?

To reproduce:

```curl --location --request POST 'http://localhost:4000/config' \
--header 'Content-Type: application/json' \
--data-raw '{"name": "Dave", "role": "SR", "gps": "", "wallet": true}'```

**Comment by sobolev-alexey** [comment]
This is fixed
